### ISSUE TITLE
Uglify breaks RickShaw

### ISSUE THREAD

**Issue by kursion** [brunch/terser-brunch#12]
Hi,

it seems that Uglify doesn't work very well with D3JS (v3.0) and also with RickShaw.

When uglified there is an error for RickShaw:

"Uncaught TypeError: undefined is not a function "

Best regards

**Comment by mathilde-pellerin** [comment]
Hi, 
this is a known problem, as you can see in this Rickshaw issue: https://github.com/shutterstock/rickshaw/issues/52

This comment https://github.com/shutterstock/rickshaw/issues/52#issuecomment-42074627 provide a solution working for requireJS. I test it with brunch that way:
```
plugins: {
	uglify:{
		except: ["$super"]
	}
},
```
but it didn't work. Is except option managed by uglify-js-brunch plugin?

**Comment by es128** [comment]
All the options are passed through as-is https://github.com/brunch/uglify-js-brunch/blob/master/index.js#L53

So if it works directly with the uglify js api it should work here.

**Comment by mathilde-pellerin** [comment]
Just tried this 
```
plugins: {
    uglify:{
        mangle: false
    }
},
```
and it works just fine :)

Hope this workaround will be useful for others, cause it's better than put Rickshaw in asset folder.
