### ISSUE TITLE
Optimizing of ../priv/static/js/app.js failed. L12175:31 SyntaxError: Unexpected token: operator (>) 

### ISSUE THREAD

**Issue by English3000** [brunch/terser-brunch#43]
Able to build [this project](https://github.com/English3000/Elixir/tree/master/functional_design/islands) (that uses `react-native-web`) in dev.

But when I run `yarn deploy`, I get the entitled error.

Looked around online to no avail...

----

OK, ran `PORT=4000 MIX_ENV=prod mix phx.server` and my app was working fine (NOT getting [the error](https://hexdocs.pm/phoenix/deployment.html#compiling-your-application-assets) from the Phoenix deploy guide).

So any idea why I'm getting `404`s for all static assets when I actually deploy? My assumption is because of this build error...

**Comment by paulmillr** [comment]
shitty error — sorry bro
